from tkinter import *
def show():
    print("Name:",name_var.get())
    print("Email:",email_var.get())
    print("Password:",pass_var.get())
    print("Gender",gender_var.get())
    print("Course:",course_var.get())
    print("=========================")
window=Tk()
window.title("Registration Form")
window.geometry("350x400")
Label(window,text="Registration Form",font=("Arial",16,"bold")).pack(pady=10)
Label(window,text="Name").pack()
name_var=StringVar()
Entry(window,textvariable=name_var,width=30).pack(pady=5)

Label(window,text="Email").pack()
email_var=StringVar()
Entry(window,textvariable=email_var,width=30).pack(pady=5)

Label(window,text="Password").pack()
pass_var=StringVar()
Entry(window,textvariable=pass_var,width=30,show="*").pack(pady=5)

Label(window,text="Gender").pack()
gender_var=StringVar()
Radiobutton(window,text="Male",variable=gender_var,value="Male").pack()
Radiobutton(window,text="Female",variable=gender_var,value="Female").pack()
Label(window,text="Course").pack()
course_var=StringVar()
course_var.set("BCA")
OptionMenu(window,course_var,"BBA","Btech","BA","BSC").pack(pady=10)
Button(window,text="Submit",command=show).pack()
window.mainloop()